apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-select-winner
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: select-winner-container
            image: curlimages/curl:latest
            command:
              - "curl"
              - "-X"
              - "GET"
              - "http://{{ .Release.Name }}-service:8000/tokens/winner/"
          restartPolicy: OnFailure
