apiVersion: v1
kind: Service
metadata:
  name: {{ include "token-generator-k8s.fullname" . }}
  labels:
    {{- include "token-generator-k8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort | default "" }}
  selector:
    {{- include "token-generator-k8s.selectorLabels" . | nindent 4 }}
