name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout code
      uses: actions/checkout@v3
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dssd-k8s-token-generator:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/dssd-k8s-token-generator:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/nombre-imagen:latest
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/dssd-k8s-token-generator:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/dssd-k8s-token-generator:latest
